// Generated by Skyramp v1.3.35 on 2026-07-22 18:14:41.816983681 +0000 UTC m=+1247.625480127
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output add-dashboard-folder-switch-stale-duplicate-check.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Dashboards \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/add_dashboard_folder_switch_stale_duplicate_check_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import PageManager from '../../pages/page-manager';

const pageTimeout = 15000;

// Test data
const uniqueSuffix = Date.now();
const folderName = "TeamReports_" + uniqueSuffix;
const dashboardName = "Repro Dash " + uniqueSuffix;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(432000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page);

    // Page objects
    const pm = new PageManager(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto("http://localhost:5080/web/dashboards?org_identifier=default");
    await pm.loginPage.login();

    /*----- Create a folder, and a dashboard inside it (setup) -----*/
    await pm.dashboardFolder.createFolder(folderName);
    // Wait for network activities to finish
    await skyrampPage.waitForTimeout(3000);

    await pm.dashboardFolder.openFolderByName(folderName);

    // Probe: at this point the newly-created folder is not yet in the
    // Add-Dashboard dialog's folder dropdown (store.state.organizationData.folders
    // hasn't refreshed) — confirmed via search returning "No options found".
    // Cancelled without submitting; reload below refreshes the store instead.
    await pm.dashboardCreate.dashCreateBtn.click();
    await skyrampPage.locator('[data-test="index-dropdown-stream_type-trigger"]').click();
    await skyrampPage.locator('[data-test="index-dropdown-stream_type-search"]').fill("Team");
    await skyrampPage.keyboard.press("Escape");
    await skyrampPage.locator('[data-test="o-dialog-secondary-btn"]').click();

    // Reload to refresh the stale folders store (not a hardcoded folder-id goto)
    await skyrampPage.reload();

    await pm.dashboardCreate.createDashboard(dashboardName);

    /*----- Switch to the default folder (empty of dashboardName) and open New Dashboard -----*/
    await pm.dashboardCreate.backToDashboardList();
    await pm.dashboardCreate.defaultFolderTab.click();
    await pm.dashboardCreate.dashCreateBtn.click();

    /*----- Switch the in-dialog folder dropdown to the folder that already has dashboardName -----*/
    await skyrampPage.locator('[data-test="index-dropdown-stream_type-trigger"]').click();
    await skyrampPage.getByRole("option", { name: folderName }).click();

    /*----- Submit the duplicate name — the schema was captured once at dialog mount
       against the ORIGINAL (default) folder's empty list, so switching the folder
       selection does not rewire the validator against the new folder's dashboards -----*/
    await pm.dashboardCreate.dashName.fill(dashboardName);
    // Wait to finish any potential hydration
    await skyrampPage.waitForTimeout(1500);
    await pm.dashboardCreate.submitBtn.click();
    // Wait for network activities to finish
    await skyrampPage.waitForTimeout(3000);

    await pm.dashboardCreate.backToDashboardList();

    /*----- Assert the correct (intended) outcome: the folder should still have only
       ONE dashboard named dashboardName. This FAILS on the current buggy code,
       which lets the duplicate through because OForm never re-registers the
       schema captured at mount — that is the documented bug. -----*/
    await expect(skyrampPage.locator(`[data-test="dashboard-name-cell-${dashboardName}"]`)).toHaveCount(1);
});
