// Generated by Skyramp v1.3.35 on 2026-07-22 18:07:11.387271637 +0000 UTC m=+797.195768093
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output add-dashboard-duplicate-name-same-folder-rejected.spec.ts \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Dashboards \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/add_dashboard_duplicate_name_same_folder_rejected_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import PageManager from '../../pages/page-manager';

const pageTimeout = 15000;

// Test data
const dashboardName = "Sales Overview";
const duplicateDashboardName = "sales overview";

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(990000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page);

    // Page objects
    const pm = new PageManager(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto("http://localhost:5080/web/login");
    await pm.loginPage.login();

    /*----- Create the first dashboard (happy path) -----*/
    await skyrampPage.goto("http://localhost:5080/web/dashboards?org_identifier=default");
    await pm.dashboardCreate.createDashboard(dashboardName);

    /*----- Attempt a case-insensitive duplicate name in the same folder -----*/
    await pm.dashboardCreate.backToDashboardList();
    await pm.dashboardCreate.dashCreateBtn.click();
    await pm.dashboardCreate.dashName.waitFor({ state: "visible", timeout: 30000 });
    await pm.dashboardCreate.dashName.fill(duplicateDashboardName);
    // Wait to finish any potential hydration
    await skyrampPage.waitForTimeout(1500);
    // Submitting a duplicate name is expected to be rejected client-side —
    // no dashboards API call fires, so no responsePromise/network wait here.
    await pm.dashboardCreate.submitBtn.click();

    /*----- Assert the duplicate-name validation error blocks submission -----*/
    await expect(skyrampPage.getByRole("alert", { name: "A dashboard with this name already exists in this folder" })).toBeVisible();
    await expect(skyrampPage.getByRole("textbox", { name: "Name" })).toHaveValue(duplicateDashboardName);
});
