// Generated by Skyramp v1.3.35 on 2026-07-27 15:24:40.819744535 +0000 UTC m=+1539.795379282
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output dashboard-panel-count-decrements-on-delete.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Dashboards \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/dashboard_panel_count_decrements_on_delete_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import PageManager from '../../pages/page-manager';

const pageTimeout = 15000;

// Test data
const dashboardName = `Panel Count Delete Test_${Date.now()}`;
const panelOneName = 'Panel One';
const panelTwoName = 'Panel Two';

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(316000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page);

    // Page object instances
    const pm = new PageManager(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto("http://localhost:5080/web/login");
    await pm.loginPage.login();

    /*----- Create dashboard with two panels -----*/
    await skyrampPage.goto("http://localhost:5080/web/dashboards?org_identifier=default");
    await pm.dashboardCreate.createDashboard(dashboardName);

    await pm.dashboardCreate.addPanel();
    await skyrampPage.locator("[data-test=\"dashboard-panel-name-field\"]").fill(panelOneName);
    await skyrampPage.getByRole("img", { name: "Markdown" }).click();
    await skyrampPage.getByRole("textbox", { name: "Editor content" }).fill("# Panel One");
    // Wait to finish any potential hydration
    await skyrampPage.waitForTimeout(1500);
    const responsePromise1 = skyrampPage.waitForResponse("**/api/**/dashboards/**");
    await skyrampPage.locator("[data-test=\"dashboard-panel-save\"]").click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Wait for network activities to finish
    await skyrampPage.waitForTimeout(3000);

    await skyrampPage.locator("[data-test=\"dashboard-refresh-btn\"]").click();
    await pm.dashboardCreate.addPanelToExistingDashboard();
    await skyrampPage.locator("[data-test=\"dashboard-panel-name-field\"]").fill(panelTwoName);
    await skyrampPage.getByRole("img", { name: "Markdown" }).click();
    await skyrampPage.getByRole("textbox", { name: "Editor content" }).fill("# Panel Two");
    // Wait to finish any potential hydration
    await skyrampPage.waitForTimeout(1500);
    const responsePromise2 = skyrampPage.waitForResponse("**/api/**/dashboards/**");
    await skyrampPage.locator("[data-test=\"dashboard-panel-save\"]").click();
    const response2 = await responsePromise2;
    expect(response2.status()).toBe(200);

    // Wait for network activities to finish
    await skyrampPage.waitForTimeout(3000);

    // Boundary: 2 panels renders the plural "panels" branch
    await expect(skyrampPage.getByRole("heading", { name: `${dashboardName}2` })).toHaveText(`${dashboardName}2 panels`);

    /*----- Delete Panel Two and verify the count decrements -----*/
    // raw fragile `page.locator("div").nth(139).getByText("Delete Panel")` replaced with
    // the POM's deletePanel(panelName) — the index-based locator breaks whenever
    // unrelated DOM structure shifts
    await pm.dashboardPanelEdit.deletePanel(panelTwoName);

    // Wait for network activities to finish
    await skyrampPage.waitForTimeout(3000);

    // Business rule: removing a panel recalculates the total, not just adding
    await expect(skyrampPage.getByRole("heading", { name: `${dashboardName}1` })).toHaveText(`${dashboardName}1 panel`);
});
