// Generated by Skyramp v1.3.35 on 2026-07-27 15:29:57.968934188 +0000 UTC m=+1856.944568935
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output dashboard-panel-count-stable-on-tab-switch.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Dashboards \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/dashboard_panel_count_stable_on_tab_switch_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import PageManager from '../../pages/page-manager';
const { getTabSelector } = require('../../pages/dashboardPages/dashboard-selectors.js');

const pageTimeout = 15000;

// Test data
const dashboardName = `Panel Count Tab Switch Test_${Date.now()}`;
const secondTabName = 'Second Tab';
const defaultTabPanelName = 'Default Tab Panel';
const secondTabPanelName = 'Second Tab Panel';

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(342000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page);

    // Page object instances
    const pm = new PageManager(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto("http://localhost:5080/web/login");
    await pm.loginPage.login();

    /*----- Create dashboard and add a panel to the Default tab -----*/
    await skyrampPage.goto("http://localhost:5080/web/dashboards?org_identifier=default");
    await pm.dashboardCreate.createDashboard(dashboardName);

    await pm.dashboardCreate.addPanel();
    await skyrampPage.locator("[data-test=\"dashboard-panel-name-field\"]").fill(defaultTabPanelName);
    await skyrampPage.getByRole("img", { name: "Markdown" }).click();
    await skyrampPage.getByRole("textbox", { name: "Editor content" }).fill("# Default tab panel");
    // Wait to finish any potential hydration
    await skyrampPage.waitForTimeout(1500);
    const responsePromise1 = skyrampPage.waitForResponse("**/api/**/dashboards/**");
    await skyrampPage.locator("[data-test=\"dashboard-panel-save\"]").click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Wait for network activities to finish
    await skyrampPage.waitForTimeout(3000);

    /*----- Add a second tab and a panel to it -----*/
    await pm.dashboardSetting.openSetting();
    await pm.dashboardSetting.addTabAndWait(secondTabName);
    await pm.dashboardSetting.closeSettingWindow();

    // raw hardcoded runtime tab id ("dashboard-tab-89163") replaced with the
    // name-based selector — the numeric id is regenerated on every run
    await skyrampPage.locator(getTabSelector(secondTabName)).click();

    await pm.dashboardCreate.addPanel();
    await skyrampPage.locator("[data-test=\"dashboard-panel-name-field\"]").fill(secondTabPanelName);
    await skyrampPage.getByRole("img", { name: "Markdown" }).click();
    await skyrampPage.getByRole("textbox", { name: "Editor content" }).fill("# Second tab panel");
    // Wait to finish any potential hydration
    await skyrampPage.waitForTimeout(1500);
    const responsePromise4 = skyrampPage.waitForResponse("**/api/**/dashboards/**");
    await skyrampPage.locator("[data-test=\"dashboard-panel-save\"]").click();
    const response4 = await responsePromise4;
    expect(response4.status()).toBe(200);

    // Wait for network activities to finish
    await skyrampPage.waitForTimeout(3000);

    // Boundary: 2 panels renders the plural "panels" branch, viewed from Second Tab
    await expect(skyrampPage.getByRole("heading", { name: `${dashboardName}2` })).toHaveText(`${dashboardName}2 panels`);

    /*----- Switch back to the Default tab and verify the count is unchanged -----*/
    await skyrampPage.locator("[data-test=\"dashboard-tab-default\"]").click();

    // Regression guard: Default tab alone has only 1 panel, but the header must
    // keep summing across ALL tabs — it must NOT drop to showing only the active tab's count
    await expect(skyrampPage.getByRole("heading", { name: `${dashboardName}2` })).toHaveText(`${dashboardName}2 panels`);
});
