// Generated by Skyramp v1.3.35 on 2026-07-27 15:13:11.324468398 +0000 UTC m=+850.300103145
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output dashboard-panel-count-sums-across-tabs.spec.js \
// 		--output-dir /home/runner/work/openobserve/openobserve/tests/ui-testing/playwright-tests/Dashboards \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/openobserve/openobserve/.skyramp/dashboard_panel_count_sums_across_tabs_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import PageManager from '../../pages/page-manager';
const { getTabSelector } = require('../../pages/dashboardPages/dashboard-selectors.js');

const pageTimeout = 15000;

// Test data
const dashboardName = `Panel Count Cross Tab Test_${Date.now()}`;
const secondTabName = 'Second Tab';
const defaultTabPanelName = 'Default Tab Panel';
const secondTabPanelName = 'Second Tab Panel';

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1515000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    const skyrampPage = newSkyrampPlaywrightPage(page);

    // Page object instances
    const pm = new PageManager(skyrampPage);

    /*----- Login -----*/
    await skyrampPage.goto("http://localhost:5080/web/login");
    await pm.loginPage.login();

    /*----- Create dashboard and add a panel to the Default tab -----*/
    await skyrampPage.goto("http://localhost:5080/web/dashboards?org_identifier=default");
    await pm.dashboardCreate.createDashboard(dashboardName);

    // Initial state: a freshly created dashboard has 0 panels (plural branch of the ternary)
    await expect(skyrampPage.getByRole("heading", { name: `${dashboardName}0` })).toHaveText(`${dashboardName}0 panels`);

    await pm.dashboardCreate.addPanel();
    await skyrampPage.locator("[data-test=\"dashboard-panel-name-field\"]").fill(defaultTabPanelName);
    await skyrampPage.getByRole("img", { name: "Markdown" }).click();
    await skyrampPage.getByRole("textbox", { name: "Editor content" }).fill("# Default tab panel");
    // Wait to finish any potential hydration
    await skyrampPage.waitForTimeout(1500);
    const responsePromise4 = skyrampPage.waitForResponse("**/api/**/dashboards/**");
    await skyrampPage.locator("[data-test=\"dashboard-panel-save\"]").click();
    const response4 = await responsePromise4;
    expect(response4.status()).toBe(200);

    // Wait for network activities to finish
    await skyrampPage.waitForTimeout(3000);

    // Boundary: exactly 1 panel renders the singular "panel" branch
    await expect(skyrampPage.getByRole("heading", { name: `${dashboardName}1` })).toHaveText(`${dashboardName}1 panel`);

    /*----- Add a second tab and a panel to it -----*/
    await pm.dashboardSetting.openSetting();
    await pm.dashboardSetting.addTabAndWait(secondTabName);
    await pm.dashboardSetting.closeSettingWindow();

    // raw hardcoded runtime tab id ("dashboard-tab-79336") replaced with the
    // name-based selector — the numeric id is regenerated on every run
    await skyrampPage.locator(getTabSelector(secondTabName)).click();

    await pm.dashboardCreate.addPanel();
    await skyrampPage.locator("[data-test=\"dashboard-panel-name-field\"]").fill(secondTabPanelName);
    await skyrampPage.getByRole("img", { name: "Markdown" }).click();
    await skyrampPage.getByRole("textbox", { name: "Editor content" }).fill("# Second tab panel");
    // Wait to finish any potential hydration
    await skyrampPage.waitForTimeout(1500);
    const responsePromise6 = skyrampPage.waitForResponse("**/api/**/dashboards/**");
    await skyrampPage.locator("[data-test=\"dashboard-panel-save\"]").click();
    const response6 = await responsePromise6;
    expect(response6.status()).toBe(200);

    // Wait for network activities to finish
    await skyrampPage.waitForTimeout(3000);

    // Business rule: the header sums panels across ALL tabs, not just the active one
    await expect(skyrampPage.getByRole("heading", { name: `${dashboardName}2` })).toHaveText(`${dashboardName}2 panels`);
});
