// @generated by skyramp
const {
  test,
  expect,
  navigateToBase,
} = require("../utils/enhanced-baseFixtures.js");
import PageManager from "../../pages/page-manager";

test.describe.configure({ mode: "parallel" });

test.describe("Dashboard delete (baseline)", () => {
  test.beforeEach(async ({ page }) => {
    await navigateToBase(page);
  });

  test("should delete a dashboard from the row actions", async ({ page }) => {
    const pm = new PageManager(page);
    const dashboardName = "Baseline_" + Math.random().toString(36).substr(2, 9);

    // Navigate to the dashboards list (POM reuse)
    await pm.dashboardList.menuItem("dashboards-item");
    await pm.dashboardCreate.waitForDashboardUIStable();

    // Create a dashboard (POM reuse)
    await pm.dashboardCreate.createDashboard(dashboardName);
    await pm.dashboardCreate.backToDashboardList();

    // Locate the row
    await page
      .locator('[data-test="dashboard-folder-tab-default"]')
      .waitFor({ state: "visible" });
    await pm.dashboardCreate.searchDashboard(dashboardName);

    // Delete — INLINE direct click on the row's delete button (pre-refactor interaction).
    // This is the line the overflow-menu refactor breaks.
    const row = page.locator('[data-test="dashboard-table"]');
    await row.waitFor({ state: "visible" });
    await row.locator('[data-test="dashboard-delete"]').first().click();

    // Confirm deletion
    const confirmDialog = page.locator('[data-test="dashboard-confirm-dialog"]');
    await confirmDialog.waitFor({ state: "visible" });
    await confirmDialog.locator('[data-test="o-dialog-primary-btn"]').click();

    // Assert the success toast (exact existing string)
    await expect(
      page.locator(
        '[data-test-variant="success"][data-test-message="Dashboard deleted successfully."]'
      )
    ).toBeVisible();
  });
});
